name: Deploy to EC2 Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd app
          python -m pytest test_main.py -v

      - name: Build Docker image
        run: |
          docker build -t zajaczek01/devops-aws-demo:latest -f docker/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push zajaczek01/devops-aws-demo:latest

      - name: Sync code to production server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER_PROD }}
          key: ${{ secrets.EC2_SSH_KEY_PROD }}
          source: "."
          target: "~/devops-aws-demo"

      - name: Deploy on EC2 Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER_PROD }}
          key: ${{ secrets.EC2_SSH_KEY_PROD }}
          script: |
            chmod +x ~/devops-aws-demo/scripts/deploy.sh
            chmod +x ~/devops-aws-demo/scripts/setup-monitoring.sh
            cd ~/devops-aws-demo/scripts
            ./deploy.sh

      - name: Verify production deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER_PROD }}
          key: ${{ secrets.EC2_SSH_KEY_PROD }}
          script: |
            sleep 30
            if curl -f http://localhost:5000/health > /dev/null 2>&1; then
              echo "✅ Production deployment verification successful!"
              echo "🌐 Production App URL: http://${{ secrets.EC2_HOST_PROD }}:5000"
              echo "📊 Production Metrics: http://${{ secrets.EC2_HOST_PROD }}:5000/metrics"
              echo "📈 Production Grafana: http://${{ secrets.EC2_HOST_PROD }}:3000"
            else
              echo "❌ Production deployment verification failed!"
              exit 1
            fi 